product=input("Product Brought:")
quantity=input("How much do you need?")
price=input("Enter price")
bill=int(quantity)*float(price)
print()
print()
print("-------------------------")
print("Your Invoice:")
print("1. Product:",product)
print("2. Quantity:",quantity)
print("3. Price:", price)
print("Your bill is", bill)